# This file was automagically generated by mbed.org. For more information, 
# see http://mbed.org/handbook/Exporting-to-GCC-ARM-Embedded

###############################################################################
# Boiler-plate

# cross-platform directory manipulation
ifeq ($(shell echo $$OS),$$OS)
    MAKEDIR = if not exist "$(1)" mkdir "$(1)"
    RM = rmdir /S /Q "$(1)"
else
    MAKEDIR = '$(SHELL)' -c "mkdir -p \"$(1)\""
    RM = '$(SHELL)' -c "rm -rf \"$(1)\""
endif

OBJDIR := BUILD
# Move to the build directory
ifeq (,$(filter $(OBJDIR),$(notdir $(CURDIR))))
.SUFFIXES:
mkfile_path := $(abspath $(lastword $(MAKEFILE_LIST)))
MAKETARGET = '$(MAKE)' --no-print-directory -C $(OBJDIR) -f '$(mkfile_path)' \
		'SRCDIR=$(CURDIR)' $(MAKECMDGOALS)
.PHONY: $(OBJDIR) clean
all:
	+@$(call MAKEDIR,$(OBJDIR))
	+@$(MAKETARGET)
$(OBJDIR): all
Makefile : ;
% :: $(OBJDIR) ; :
clean :
	$(call RM,$(OBJDIR))

else

# trick rules into thinking we are in the root, when we are in the bulid dir
VPATH = ..

# Boiler-plate
###############################################################################
# Project settings

PROJECT := DiscoF746_tgfx


# Project settings
###############################################################################
# Objects and Paths

OBJECTS += ./lib/BSP_DISCO_F746NG/Drivers/BSP/Components/ft5336/ft5336.o
OBJECTS += ./lib/BSP_DISCO_F746NG/Drivers/BSP/Components/ov9655/ov9655.o
OBJECTS += ./lib/BSP_DISCO_F746NG/Drivers/BSP/Components/wm8994/wm8994.o
OBJECTS += ./lib/BSP_DISCO_F746NG/Drivers/BSP/STM32746G-Discovery/stm32746g_discovery.o
OBJECTS += ./lib/BSP_DISCO_F746NG/Drivers/BSP/STM32746G-Discovery/stm32746g_discovery_audio.o
OBJECTS += ./lib/BSP_DISCO_F746NG/Drivers/BSP/STM32746G-Discovery/stm32746g_discovery_camera.o
OBJECTS += ./lib/BSP_DISCO_F746NG/Drivers/BSP/STM32746G-Discovery/stm32746g_discovery_eeprom.o
OBJECTS += ./lib/BSP_DISCO_F746NG/Drivers/BSP/STM32746G-Discovery/stm32746g_discovery_lcd.o
OBJECTS += ./lib/BSP_DISCO_F746NG/Drivers/BSP/STM32746G-Discovery/stm32746g_discovery_qspi.o
OBJECTS += ./lib/BSP_DISCO_F746NG/Drivers/BSP/STM32746G-Discovery/stm32746g_discovery_sd.o
OBJECTS += ./lib/BSP_DISCO_F746NG/Drivers/BSP/STM32746G-Discovery/stm32746g_discovery_sdram.o
OBJECTS += ./lib/BSP_DISCO_F746NG/Drivers/BSP/STM32746G-Discovery/stm32746g_discovery_ts.o
OBJECTS += ./lib/BSP_DISCO_F746NG/Utilities/Fonts/font12.o
OBJECTS += ./lib/BSP_DISCO_F746NG/Utilities/Fonts/font16.o
OBJECTS += ./lib/BSP_DISCO_F746NG/Utilities/Fonts/font20.o
OBJECTS += ./lib/BSP_DISCO_F746NG/Utilities/Fonts/font24.o
OBJECTS += ./lib/BSP_DISCO_F746NG/Utilities/Fonts/font8.o
OBJECTS += ./lib/LCD_DISCO_F746NG/LCD_DISCO_F746NG.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/containers/CacheableContainer.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/containers/Container.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/containers/ListLayout.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/containers/ModalWindow.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/containers/ScrollableContainer.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/containers/SlideMenu.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/containers/Slider.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/containers/SwipeContainer.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/containers/ZoomAnimationImage.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/containers/clock/AbstractClock.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/containers/clock/AnalogClock.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/containers/clock/DigitalClock.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/containers/progress_indicators/AbstractDirectionProgress.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/containers/progress_indicators/AbstractProgressIndicator.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/containers/progress_indicators/BoxProgress.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/containers/progress_indicators/CircleProgress.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/containers/progress_indicators/ImageProgress.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/containers/progress_indicators/LineProgress.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/containers/progress_indicators/TextProgress.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/containers/scrollers/DrawableList.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/containers/scrollers/ScrollBase.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/containers/scrollers/ScrollList.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/containers/scrollers/ScrollWheel.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/containers/scrollers/ScrollWheelBase.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/containers/scrollers/ScrollWheelWithSelectionStyle.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/AbstractButton.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/AnimatedImage.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/AnimationTextureMapper.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/Box.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/BoxWithBorder.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/Button.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/ButtonWithIcon.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/ButtonWithLabel.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/Image.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/Keyboard.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/PixelDataWidget.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/RadioButton.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/RepeatButton.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/ScalableImage.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/SnapshotWidget.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/TextArea.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/TextAreaWithWildcard.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/TextureMapper.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/TiledImage.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/ToggleButton.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/TouchArea.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/AbstractPainterABGR2222.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/AbstractPainterARGB2222.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/AbstractPainterARGB8888.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/AbstractPainterBGRA2222.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/AbstractPainterBW.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/AbstractPainterGRAY2.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/AbstractPainterGRAY4.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/AbstractPainterRGB565.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/AbstractPainterRGB888.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/AbstractPainterRGBA2222.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/AbstractShape.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/Canvas.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/CanvasWidget.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/Circle.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/Line.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/PainterABGR2222.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/PainterABGR2222Bitmap.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/PainterARGB2222.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/PainterARGB2222Bitmap.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/PainterARGB8888.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/PainterARGB8888Bitmap.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/PainterARGB8888L8Bitmap.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/PainterBGRA2222.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/PainterBGRA2222Bitmap.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/PainterBW.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/PainterBWBitmap.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/PainterGRAY2.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/PainterGRAY2Bitmap.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/PainterGRAY4.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/PainterGRAY4Bitmap.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/PainterRGB565.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/PainterRGB565Bitmap.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/PainterRGB565L8Bitmap.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/PainterRGB888.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/PainterRGB888Bitmap.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/PainterRGB888L8Bitmap.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/PainterRGBA2222.o
OBJECTS += ./lib/touchgfx/framework/source/touchgfx/widgets/canvas/PainterRGBA2222Bitmap.o
OBJECTS += ./mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Config/RTX_Config.o
OBJECTS += ./mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Library/cmsis_os1.o
OBJECTS += ./mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/TOOLCHAIN_GCC/TARGET_RTOS_M4_M7/irq_cm4f.o
OBJECTS += ./mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_delay.o
OBJECTS += ./mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_evflags.o
OBJECTS += ./mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_evr.o
OBJECTS += ./mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_kernel.o
OBJECTS += ./mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_lib.o
OBJECTS += ./mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_memory.o
OBJECTS += ./mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_mempool.o
OBJECTS += ./mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_msgqueue.o
OBJECTS += ./mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_mutex.o
OBJECTS += ./mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_semaphore.o
OBJECTS += ./mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_system.o
OBJECTS += ./mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_thread.o
OBJECTS += ./mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_timer.o
OBJECTS += ./mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/Source/os_systick.o
OBJECTS += ./mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/Source/os_tick_ptim.o
OBJECTS += ./mbed-os/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Source/mbed_tz_context.o
OBJECTS += ./mbed-os/cmsis/device/rtos/TOOLCHAIN_GCC_ARM/mbed_boot_gcc_arm.o
OBJECTS += ./mbed-os/cmsis/device/rtos/source/mbed_boot.o
OBJECTS += ./mbed-os/cmsis/device/rtos/source/mbed_rtos_rtx.o
OBJECTS += ./mbed-os/cmsis/device/rtos/source/mbed_rtx_handlers.o
OBJECTS += ./mbed-os/cmsis/device/rtos/source/mbed_rtx_idle.o
OBJECTS += ./mbed-os/connectivity/libraries/nanostack-libservice/source/IPv6_fcf_lib/ip_fsc.o
OBJECTS += ./mbed-os/connectivity/libraries/nanostack-libservice/source/libBits/common_functions.o
OBJECTS += ./mbed-os/connectivity/libraries/nanostack-libservice/source/libList/ns_list.o
OBJECTS += ./mbed-os/connectivity/libraries/nanostack-libservice/source/libip4string/ip4tos.o
OBJECTS += ./mbed-os/connectivity/libraries/nanostack-libservice/source/libip4string/stoip4.o
OBJECTS += ./mbed-os/connectivity/libraries/nanostack-libservice/source/libip6string/ip6tos.o
OBJECTS += ./mbed-os/connectivity/libraries/nanostack-libservice/source/libip6string/stoip6.o
OBJECTS += ./mbed-os/connectivity/libraries/nanostack-libservice/source/nsdynmemLIB/nsdynmemLIB.o
OBJECTS += ./mbed-os/connectivity/libraries/nanostack-libservice/source/nvmHelper/ns_nvm_helper.o
OBJECTS += ./mbed-os/drivers/source/AnalogIn.o
OBJECTS += ./mbed-os/drivers/source/AnalogOut.o
OBJECTS += ./mbed-os/drivers/source/BufferedSerial.o
OBJECTS += ./mbed-os/drivers/source/BusIn.o
OBJECTS += ./mbed-os/drivers/source/BusInOut.o
OBJECTS += ./mbed-os/drivers/source/BusOut.o
OBJECTS += ./mbed-os/drivers/source/CAN.o
OBJECTS += ./mbed-os/drivers/source/DigitalIn.o
OBJECTS += ./mbed-os/drivers/source/DigitalInOut.o
OBJECTS += ./mbed-os/drivers/source/DigitalOut.o
OBJECTS += ./mbed-os/drivers/source/FlashIAP.o
OBJECTS += ./mbed-os/drivers/source/I2C.o
OBJECTS += ./mbed-os/drivers/source/I2CSlave.o
OBJECTS += ./mbed-os/drivers/source/InterruptIn.o
OBJECTS += ./mbed-os/drivers/source/MbedCRC.o
OBJECTS += ./mbed-os/drivers/source/PortIn.o
OBJECTS += ./mbed-os/drivers/source/PortInOut.o
OBJECTS += ./mbed-os/drivers/source/PortOut.o
OBJECTS += ./mbed-os/drivers/source/PwmOut.o
OBJECTS += ./mbed-os/drivers/source/QSPI.o
OBJECTS += ./mbed-os/drivers/source/ResetReason.o
OBJECTS += ./mbed-os/drivers/source/SFDP.o
OBJECTS += ./mbed-os/drivers/source/SPI.o
OBJECTS += ./mbed-os/drivers/source/SPISlave.o
OBJECTS += ./mbed-os/drivers/source/SerialBase.o
OBJECTS += ./mbed-os/drivers/source/SerialWireOutput.o
OBJECTS += ./mbed-os/drivers/source/Ticker.o
OBJECTS += ./mbed-os/drivers/source/Timeout.o
OBJECTS += ./mbed-os/drivers/source/Timer.o
OBJECTS += ./mbed-os/drivers/source/TimerEvent.o
OBJECTS += ./mbed-os/drivers/source/UnbufferedSerial.o
OBJECTS += ./mbed-os/drivers/source/Watchdog.o
OBJECTS += ./mbed-os/drivers/source/usb/AsyncOp.o
OBJECTS += ./mbed-os/drivers/source/usb/ByteBuffer.o
OBJECTS += ./mbed-os/drivers/source/usb/EndpointResolver.o
OBJECTS += ./mbed-os/drivers/source/usb/LinkedListBase.o
OBJECTS += ./mbed-os/drivers/source/usb/OperationListBase.o
OBJECTS += ./mbed-os/drivers/source/usb/PolledQueue.o
OBJECTS += ./mbed-os/drivers/source/usb/TaskBase.o
OBJECTS += ./mbed-os/drivers/source/usb/USBAudio.o
OBJECTS += ./mbed-os/drivers/source/usb/USBCDC.o
OBJECTS += ./mbed-os/drivers/source/usb/USBCDC_ECM.o
OBJECTS += ./mbed-os/drivers/source/usb/USBDevice.o
OBJECTS += ./mbed-os/drivers/source/usb/USBHID.o
OBJECTS += ./mbed-os/drivers/source/usb/USBKeyboard.o
OBJECTS += ./mbed-os/drivers/source/usb/USBMIDI.o
OBJECTS += ./mbed-os/drivers/source/usb/USBMSD.o
OBJECTS += ./mbed-os/drivers/source/usb/USBMouse.o
OBJECTS += ./mbed-os/drivers/source/usb/USBMouseKeyboard.o
OBJECTS += ./mbed-os/drivers/source/usb/USBSerial.o
OBJECTS += ./mbed-os/events/source/EventQueue.o
OBJECTS += ./mbed-os/events/source/equeue.o
OBJECTS += ./mbed-os/events/source/equeue_mbed.o
OBJECTS += ./mbed-os/events/source/equeue_posix.o
OBJECTS += ./mbed-os/events/source/mbed_shared_queues.o
OBJECTS += ./mbed-os/features/frameworks/mbed-trace/source/mbed_trace.o
OBJECTS += ./mbed-os/hal/source/LowPowerTickerWrapper.o
OBJECTS += ./mbed-os/hal/source/mbed_compat.o
OBJECTS += ./mbed-os/hal/source/mbed_critical_section_api.o
OBJECTS += ./mbed-os/hal/source/mbed_flash_api.o
OBJECTS += ./mbed-os/hal/source/mbed_gpio.o
OBJECTS += ./mbed-os/hal/source/mbed_gpio_irq.o
OBJECTS += ./mbed-os/hal/source/mbed_itm_api.o
OBJECTS += ./mbed-os/hal/source/mbed_lp_ticker_api.o
OBJECTS += ./mbed-os/hal/source/mbed_lp_ticker_wrapper.o
OBJECTS += ./mbed-os/hal/source/mbed_pinmap_common.o
OBJECTS += ./mbed-os/hal/source/mbed_pinmap_default.o
OBJECTS += ./mbed-os/hal/source/mbed_ticker_api.o
OBJECTS += ./mbed-os/hal/source/mbed_us_ticker_api.o
OBJECTS += ./mbed-os/hal/source/mpu/mbed_mpu_v7m.o
OBJECTS += ./mbed-os/hal/source/mpu/mbed_mpu_v8m.o
OBJECTS += ./mbed-os/hal/source/static_pinmap.o
OBJECTS += ./mbed-os/hal/usb/source/mbed_usb_phy.o
OBJECTS += ./mbed-os/platform/cxxsupport/mstd_mutex.o
OBJECTS += ./mbed-os/platform/source/ATCmdParser.o
OBJECTS += ./mbed-os/platform/source/CThunkBase.o
OBJECTS += ./mbed-os/platform/source/CriticalSectionLock.o
OBJECTS += ./mbed-os/platform/source/DeepSleepLock.o
OBJECTS += ./mbed-os/platform/source/FileBase.o
OBJECTS += ./mbed-os/platform/source/FileHandle.o
OBJECTS += ./mbed-os/platform/source/FilePath.o
OBJECTS += ./mbed-os/platform/source/FileSystemHandle.o
OBJECTS += ./mbed-os/platform/source/LocalFileSystem.o
OBJECTS += ./mbed-os/platform/source/Stream.o
OBJECTS += ./mbed-os/platform/source/SysTimer.o
OBJECTS += ./mbed-os/platform/source/TARGET_CORTEX_M/TOOLCHAIN_GCC/except.o
OBJECTS += ./mbed-os/platform/source/TARGET_CORTEX_M/mbed_fault_handler.o
OBJECTS += ./mbed-os/platform/source/mbed_alloc_wrappers.o
OBJECTS += ./mbed-os/platform/source/mbed_application.o
OBJECTS += ./mbed-os/platform/source/mbed_assert.o
OBJECTS += ./mbed-os/platform/source/mbed_atomic_impl.o
OBJECTS += ./mbed-os/platform/source/mbed_board.o
OBJECTS += ./mbed-os/platform/source/mbed_critical.o
OBJECTS += ./mbed-os/platform/source/mbed_error.o
OBJECTS += ./mbed-os/platform/source/mbed_error_hist.o
OBJECTS += ./mbed-os/platform/source/mbed_interface.o
OBJECTS += ./mbed-os/platform/source/mbed_mem_trace.o
OBJECTS += ./mbed-os/platform/source/mbed_mktime.o
OBJECTS += ./mbed-os/platform/source/mbed_mpu_mgmt.o
OBJECTS += ./mbed-os/platform/source/mbed_os_timer.o
OBJECTS += ./mbed-os/platform/source/mbed_poll.o
OBJECTS += ./mbed-os/platform/source/mbed_power_mgmt.o
OBJECTS += ./mbed-os/platform/source/mbed_retarget.o
OBJECTS += ./mbed-os/platform/source/mbed_rtc_time.o
OBJECTS += ./mbed-os/platform/source/mbed_sdk_boot.o
OBJECTS += ./mbed-os/platform/source/mbed_semihost_api.o
OBJECTS += ./mbed-os/platform/source/mbed_stats.o
OBJECTS += ./mbed-os/platform/source/mbed_thread.o
OBJECTS += ./mbed-os/platform/source/mbed_wait_api_no_rtos.o
OBJECTS += ./mbed-os/platform/source/minimal-printf/mbed_printf_armlink_overrides.o
OBJECTS += ./mbed-os/platform/source/minimal-printf/mbed_printf_implementation.o
OBJECTS += ./mbed-os/platform/source/minimal-printf/mbed_printf_wrapper.o
OBJECTS += ./mbed-os/rtos/source/ConditionVariable.o
OBJECTS += ./mbed-os/rtos/source/EventFlags.o
OBJECTS += ./mbed-os/rtos/source/Kernel.o
OBJECTS += ./mbed-os/rtos/source/Mutex.o
OBJECTS += ./mbed-os/rtos/source/Semaphore.o
OBJECTS += ./mbed-os/rtos/source/ThisThread.o
OBJECTS += ./mbed-os/rtos/source/Thread.o
OBJECTS += ./mbed-os/storage/blockdevice/COMPONENT_FLASHIAP/source/FlashIAPBlockDevice.o
OBJECTS += ./mbed-os/storage/blockdevice/COMPONENT_QSPIF/source/QSPIFBlockDevice.o
OBJECTS += ./mbed-os/storage/blockdevice/source/BufferedBlockDevice.o
OBJECTS += ./mbed-os/storage/blockdevice/source/ChainingBlockDevice.o
OBJECTS += ./mbed-os/storage/blockdevice/source/ExhaustibleBlockDevice.o
OBJECTS += ./mbed-os/storage/blockdevice/source/FlashSimBlockDevice.o
OBJECTS += ./mbed-os/storage/blockdevice/source/HeapBlockDevice.o
OBJECTS += ./mbed-os/storage/blockdevice/source/MBRBlockDevice.o
OBJECTS += ./mbed-os/storage/blockdevice/source/ObservingBlockDevice.o
OBJECTS += ./mbed-os/storage/blockdevice/source/ProfilingBlockDevice.o
OBJECTS += ./mbed-os/storage/blockdevice/source/ReadOnlyBlockDevice.o
OBJECTS += ./mbed-os/storage/blockdevice/source/SlicingBlockDevice.o
OBJECTS += ./mbed-os/storage/filesystem/fat/ChaN/ff.o
OBJECTS += ./mbed-os/storage/filesystem/fat/ChaN/ffunicode.o
OBJECTS += ./mbed-os/storage/filesystem/fat/source/FATFileSystem.o
OBJECTS += ./mbed-os/storage/filesystem/littlefs/littlefs/lfs.o
OBJECTS += ./mbed-os/storage/filesystem/littlefs/littlefs/lfs_util.o
OBJECTS += ./mbed-os/storage/filesystem/littlefs/source/LittleFileSystem.o
OBJECTS += ./mbed-os/storage/filesystem/littlefsv2/littlefs/lfs2.o
OBJECTS += ./mbed-os/storage/filesystem/littlefsv2/littlefs/lfs2_util.o
OBJECTS += ./mbed-os/storage/filesystem/littlefsv2/source/LittleFileSystem2.o
OBJECTS += ./mbed-os/storage/filesystem/source/Dir.o
OBJECTS += ./mbed-os/storage/filesystem/source/File.o
OBJECTS += ./mbed-os/storage/filesystem/source/FileSystem.o
OBJECTS += ./mbed-os/storage/platform/source/PlatformStorage.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/Legacy/stm32f7xx_hal_can_legacy.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_adc.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_adc_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_can.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_cec.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_cortex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_crc.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_crc_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_cryp.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_cryp_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_dac.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_dac_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_dcmi.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_dcmi_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_dfsdm.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_dma.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_dma2d.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_dma_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_dsi.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_eth.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_exti.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_flash.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_flash_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_gpio.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_hash.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_hash_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_hcd.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_i2c.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_i2c_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_i2s.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_irda.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_iwdg.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_jpeg.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_lptim.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_ltdc.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_ltdc_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_mdios.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_mmc.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_nand.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_nor.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_pcd.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_pcd_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_pwr.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_pwr_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_qspi.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_rcc.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_rcc_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_rng.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_rtc.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_rtc_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_sai.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_sai_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_sd.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_sdram.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_smartcard.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_smartcard_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_smbus.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_spdifrx.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_spi.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_spi_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_sram.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_tim.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_tim_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_uart.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_uart_ex.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_usart.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_wwdg.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_adc.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_crc.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_dac.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_dma.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_dma2d.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_exti.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_fmc.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_gpio.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_i2c.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_lptim.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_pwr.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_rcc.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_rng.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_rtc.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_sdmmc.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_spi.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_tim.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_usart.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_usb.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_utils.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/system_stm32f7xx.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_DISCO_F746NG/PeripheralPins.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_DISCO_F746NG/system_clock.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TOOLCHAIN_GCC_ARM/startup_stm32f746xx.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/analogin_device.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/analogout_device.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/flash_api.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/gpio_irq_device.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/pwmout_device.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/serial_device.o
OBJECTS += ./mbed-os/targets/TARGET_STM/TARGET_STM32F7/spi_api.o
OBJECTS += ./mbed-os/targets/TARGET_STM/USBPhy_STM32.o
OBJECTS += ./mbed-os/targets/TARGET_STM/analogin_api.o
OBJECTS += ./mbed-os/targets/TARGET_STM/analogout_api.o
OBJECTS += ./mbed-os/targets/TARGET_STM/can_api.o
OBJECTS += ./mbed-os/targets/TARGET_STM/gpio_api.o
OBJECTS += ./mbed-os/targets/TARGET_STM/gpio_irq_api.o
OBJECTS += ./mbed-os/targets/TARGET_STM/hal_tick_overrides.o
OBJECTS += ./mbed-os/targets/TARGET_STM/i2c_api.o
OBJECTS += ./mbed-os/targets/TARGET_STM/lp_ticker.o
OBJECTS += ./mbed-os/targets/TARGET_STM/mbed_crc_api.o
OBJECTS += ./mbed-os/targets/TARGET_STM/mbed_overrides.o
OBJECTS += ./mbed-os/targets/TARGET_STM/pinmap.o
OBJECTS += ./mbed-os/targets/TARGET_STM/port_api.o
OBJECTS += ./mbed-os/targets/TARGET_STM/pwmout_api.o
OBJECTS += ./mbed-os/targets/TARGET_STM/qspi_api.o
OBJECTS += ./mbed-os/targets/TARGET_STM/reset_reason.o
OBJECTS += ./mbed-os/targets/TARGET_STM/rtc_api.o
OBJECTS += ./mbed-os/targets/TARGET_STM/serial_api.o
OBJECTS += ./mbed-os/targets/TARGET_STM/sleep.o
OBJECTS += ./mbed-os/targets/TARGET_STM/stm_spi_api.o
OBJECTS += ./mbed-os/targets/TARGET_STM/trng_api.o
OBJECTS += ./mbed-os/targets/TARGET_STM/us_ticker.o
OBJECTS += ./mbed-os/targets/TARGET_STM/watchdog_api.o
OBJECTS += ./src/BoardConfiguration.o
OBJECTS += ./src/OSWrappers.o
OBJECTS += ./src/STM32F746GTouchController.o
OBJECTS += ./src/STM32F7DMA.o
OBJECTS += ./src/STM32F7HAL.o
OBJECTS += ./src/TouchGFXGPIO.o
OBJECTS += ./src/TouchGFXKeys.o
OBJECTS += ./src/generated/fonts/src/ApplicationFontProvider.o
OBJECTS += ./src/generated/fonts/src/CachedFont.o
OBJECTS += ./src/generated/fonts/src/FontCache.o
OBJECTS += ./src/generated/fonts/src/Font_verdana_10_4bpp_0.o
OBJECTS += ./src/generated/fonts/src/Font_verdana_20_4bpp_0.o
OBJECTS += ./src/generated/fonts/src/Font_verdana_40_4bpp_0.o
OBJECTS += ./src/generated/fonts/src/GeneratedFont.o
OBJECTS += ./src/generated/fonts/src/Kerning_verdana_10_4bpp.o
OBJECTS += ./src/generated/fonts/src/Kerning_verdana_20_4bpp.o
OBJECTS += ./src/generated/fonts/src/Kerning_verdana_40_4bpp.o
OBJECTS += ./src/generated/fonts/src/Table_verdana_10_4bpp.o
OBJECTS += ./src/generated/fonts/src/Table_verdana_20_4bpp.o
OBJECTS += ./src/generated/fonts/src/Table_verdana_40_4bpp.o
OBJECTS += ./src/generated/gui_generated/src/common/FrontendApplicationBase.o
OBJECTS += ./src/generated/gui_generated/src/screen1_screen/Screen1ViewBase.o
OBJECTS += ./src/generated/gui_generated/src/screen2_screen/Screen2ViewBase.o
OBJECTS += ./src/generated/images/src/BitmapDatabase.o
OBJECTS += ./src/generated/images/src/__designer/image_Blue_Backgrounds_Main_bg_texture_480x272px.o
OBJECTS += ./src/generated/images/src/__designer/image_Blue_Buttons_Round_Edge_small.o
OBJECTS += ./src/generated/images/src/__designer/image_Blue_Buttons_Round_Edge_small_pressed.o
OBJECTS += ./src/generated/images/src/__designer/image_Blue_Clocks_Backgrounds_clock_standard_background.o
OBJECTS += ./src/generated/images/src/__designer/image_Blue_Clocks_Hands_clock_standard_hour_hand.o
OBJECTS += ./src/generated/images/src/__designer/image_Blue_Clocks_Hands_clock_standard_minute_hand.o
OBJECTS += ./src/generated/images/src/__designer/image_Blue_Clocks_Hands_clock_standard_second_hand.o
OBJECTS += ./src/generated/images/src/__designer/image_Blue_Slider_Horizontal_Small_Indicators_slider_horizontal_small_round_knob.o
OBJECTS += ./src/generated/images/src/__designer/image_Blue_Slider_Horizontal_Small_slider_horizontal_small_round_back.o
OBJECTS += ./src/generated/images/src/__designer/image_Blue_Slider_Horizontal_Small_slider_horizontal_small_round_fill.o
OBJECTS += ./src/generated/images/src/__designer/image_Blue_Textures_carbon_fibre.o
OBJECTS += ./src/generated/texts/src/LanguageGb.o
OBJECTS += ./src/generated/texts/src/Texts.o
OBJECTS += ./src/generated/texts/src/TypedTextDatabase.o
OBJECTS += ./src/gui/src/common/FrontendApplication.o
OBJECTS += ./src/gui/src/model/Model.o
OBJECTS += ./src/gui/src/screen1_screen/Screen1Presenter.o
OBJECTS += ./src/gui/src/screen1_screen/Screen1View.o
OBJECTS += ./src/gui/src/screen2_screen/Screen2Presenter.o
OBJECTS += ./src/gui/src/screen2_screen/Screen2View.o
OBJECTS += ./src/main.o


INCLUDE_PATHS += -I../.
INCLUDE_PATHS += -I.././lib
INCLUDE_PATHS += -I.././lib/BSP_DISCO_F746NG
INCLUDE_PATHS += -I.././lib/BSP_DISCO_F746NG/Drivers
INCLUDE_PATHS += -I.././lib/BSP_DISCO_F746NG/Drivers/BSP
INCLUDE_PATHS += -I.././lib/BSP_DISCO_F746NG/Drivers/BSP/Components
INCLUDE_PATHS += -I.././lib/BSP_DISCO_F746NG/Drivers/BSP/Components/Common
INCLUDE_PATHS += -I.././lib/BSP_DISCO_F746NG/Drivers/BSP/Components/ft5336
INCLUDE_PATHS += -I.././lib/BSP_DISCO_F746NG/Drivers/BSP/Components/n25q128a
INCLUDE_PATHS += -I.././lib/BSP_DISCO_F746NG/Drivers/BSP/Components/ov9655
INCLUDE_PATHS += -I.././lib/BSP_DISCO_F746NG/Drivers/BSP/Components/rk043fn48h
INCLUDE_PATHS += -I.././lib/BSP_DISCO_F746NG/Drivers/BSP/Components/wm8994
INCLUDE_PATHS += -I.././lib/BSP_DISCO_F746NG/Drivers/BSP/STM32746G-Discovery
INCLUDE_PATHS += -I.././lib/BSP_DISCO_F746NG/Utilities
INCLUDE_PATHS += -I.././lib/BSP_DISCO_F746NG/Utilities/Fonts
INCLUDE_PATHS += -I.././lib/LCD_DISCO_F746NG
INCLUDE_PATHS += -I.././lib/touchgfx
INCLUDE_PATHS += -I.././lib/touchgfx/framework
INCLUDE_PATHS += -I.././lib/touchgfx/framework/include
INCLUDE_PATHS += -I.././lib/touchgfx/framework/include/common
INCLUDE_PATHS += -I.././lib/touchgfx/framework/include/mvp
INCLUDE_PATHS += -I.././lib/touchgfx/framework/include/platform
INCLUDE_PATHS += -I.././lib/touchgfx/framework/include/platform/core
INCLUDE_PATHS += -I.././lib/touchgfx/framework/include/platform/driver
INCLUDE_PATHS += -I.././lib/touchgfx/framework/include/platform/driver/button
INCLUDE_PATHS += -I.././lib/touchgfx/framework/include/platform/driver/i2c
INCLUDE_PATHS += -I.././lib/touchgfx/framework/include/platform/driver/lcd
INCLUDE_PATHS += -I.././lib/touchgfx/framework/include/platform/driver/touch
INCLUDE_PATHS += -I.././lib/touchgfx/framework/include/platform/hal
INCLUDE_PATHS += -I.././lib/touchgfx/framework/include/platform/hal/simulator
INCLUDE_PATHS += -I.././lib/touchgfx/framework/include/platform/hal/simulator/sdl2
INCLUDE_PATHS += -I.././lib/touchgfx/framework/include/platform/hal/simulator/sdl2/vendor
INCLUDE_PATHS += -I.././lib/touchgfx/framework/include/platform/hal/simulator/sdl2/vendor/SDL2
INCLUDE_PATHS += -I.././lib/touchgfx/framework/include/touchgfx
INCLUDE_PATHS += -I.././lib/touchgfx/framework/include/touchgfx/canvas_widget_renderer
INCLUDE_PATHS += -I.././lib/touchgfx/framework/include/touchgfx/containers
INCLUDE_PATHS += -I.././lib/touchgfx/framework/include/touchgfx/containers/buttons
INCLUDE_PATHS += -I.././lib/touchgfx/framework/include/touchgfx/containers/clock
INCLUDE_PATHS += -I.././lib/touchgfx/framework/include/touchgfx/containers/progress_indicators
INCLUDE_PATHS += -I.././lib/touchgfx/framework/include/touchgfx/containers/scrollers
INCLUDE_PATHS += -I.././lib/touchgfx/framework/include/touchgfx/events
INCLUDE_PATHS += -I.././lib/touchgfx/framework/include/touchgfx/hal
INCLUDE_PATHS += -I.././lib/touchgfx/framework/include/touchgfx/lcd
INCLUDE_PATHS += -I.././lib/touchgfx/framework/include/touchgfx/mixins
INCLUDE_PATHS += -I.././lib/touchgfx/framework/include/touchgfx/transforms
INCLUDE_PATHS += -I.././lib/touchgfx/framework/include/touchgfx/transitions
INCLUDE_PATHS += -I.././lib/touchgfx/framework/include/touchgfx/widgets
INCLUDE_PATHS += -I.././lib/touchgfx/framework/include/touchgfx/widgets/canvas
INCLUDE_PATHS += -I.././mbed-os
INCLUDE_PATHS += -I.././mbed-os/cmsis
INCLUDE_PATHS += -I.././mbed-os/cmsis/CMSIS_5
INCLUDE_PATHS += -I.././mbed-os/cmsis/CMSIS_5/CMSIS
INCLUDE_PATHS += -I.././mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2
INCLUDE_PATHS += -I.././mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/Include
INCLUDE_PATHS += -I.././mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX
INCLUDE_PATHS += -I.././mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Config
INCLUDE_PATHS += -I.././mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Include
INCLUDE_PATHS += -I.././mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Include1
INCLUDE_PATHS += -I.././mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source
INCLUDE_PATHS += -I.././mbed-os/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M
INCLUDE_PATHS += -I.././mbed-os/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Include
INCLUDE_PATHS += -I.././mbed-os/cmsis/device
INCLUDE_PATHS += -I.././mbed-os/cmsis/device/RTE
INCLUDE_PATHS += -I.././mbed-os/cmsis/device/RTE/include
INCLUDE_PATHS += -I.././mbed-os/cmsis/device/rtos
INCLUDE_PATHS += -I.././mbed-os/cmsis/device/rtos/include
INCLUDE_PATHS += -I.././mbed-os/connectivity
INCLUDE_PATHS += -I.././mbed-os/connectivity/libraries
INCLUDE_PATHS += -I.././mbed-os/connectivity/libraries/nanostack-libservice
INCLUDE_PATHS += -I.././mbed-os/connectivity/libraries/nanostack-libservice/mbed-client-libservice
INCLUDE_PATHS += -I.././mbed-os/connectivity/libraries/nanostack-libservice/mbed-client-libservice/platform
INCLUDE_PATHS += -I.././mbed-os/drivers
INCLUDE_PATHS += -I.././mbed-os/drivers/include
INCLUDE_PATHS += -I.././mbed-os/drivers/include/drivers
INCLUDE_PATHS += -I.././mbed-os/drivers/include/drivers/internal
INCLUDE_PATHS += -I.././mbed-os/events
INCLUDE_PATHS += -I.././mbed-os/events/include
INCLUDE_PATHS += -I.././mbed-os/events/include/events
INCLUDE_PATHS += -I.././mbed-os/events/include/events/internal
INCLUDE_PATHS += -I.././mbed-os/features
INCLUDE_PATHS += -I.././mbed-os/features/frameworks
INCLUDE_PATHS += -I.././mbed-os/features/frameworks/mbed-trace
INCLUDE_PATHS += -I.././mbed-os/features/frameworks/mbed-trace/mbed-trace
INCLUDE_PATHS += -I.././mbed-os/hal
INCLUDE_PATHS += -I.././mbed-os/hal/include
INCLUDE_PATHS += -I.././mbed-os/hal/include/hal
INCLUDE_PATHS += -I.././mbed-os/hal/usb
INCLUDE_PATHS += -I.././mbed-os/hal/usb/include
INCLUDE_PATHS += -I.././mbed-os/hal/usb/include/usb
INCLUDE_PATHS += -I.././mbed-os/platform
INCLUDE_PATHS += -I.././mbed-os/platform/cxxsupport
INCLUDE_PATHS += -I.././mbed-os/platform/include
INCLUDE_PATHS += -I.././mbed-os/platform/include/platform
INCLUDE_PATHS += -I.././mbed-os/platform/include/platform/internal
INCLUDE_PATHS += -I.././mbed-os/platform/source
INCLUDE_PATHS += -I.././mbed-os/platform/source/minimal-printf
INCLUDE_PATHS += -I.././mbed-os/rtos
INCLUDE_PATHS += -I.././mbed-os/rtos/include
INCLUDE_PATHS += -I.././mbed-os/rtos/include/rtos
INCLUDE_PATHS += -I.././mbed-os/rtos/include/rtos/internal
INCLUDE_PATHS += -I.././mbed-os/rtos/source
INCLUDE_PATHS += -I.././mbed-os/storage
INCLUDE_PATHS += -I.././mbed-os/storage/blockdevice
INCLUDE_PATHS += -I.././mbed-os/storage/blockdevice/COMPONENT_FLASHIAP
INCLUDE_PATHS += -I.././mbed-os/storage/blockdevice/COMPONENT_FLASHIAP/include
INCLUDE_PATHS += -I.././mbed-os/storage/blockdevice/COMPONENT_FLASHIAP/include/FlashIAP
INCLUDE_PATHS += -I.././mbed-os/storage/blockdevice/COMPONENT_QSPIF
INCLUDE_PATHS += -I.././mbed-os/storage/blockdevice/COMPONENT_QSPIF/include
INCLUDE_PATHS += -I.././mbed-os/storage/blockdevice/COMPONENT_QSPIF/include/QSPIF
INCLUDE_PATHS += -I.././mbed-os/storage/blockdevice/include
INCLUDE_PATHS += -I.././mbed-os/storage/blockdevice/include/blockdevice
INCLUDE_PATHS += -I.././mbed-os/storage/filesystem
INCLUDE_PATHS += -I.././mbed-os/storage/filesystem/fat
INCLUDE_PATHS += -I.././mbed-os/storage/filesystem/fat/ChaN
INCLUDE_PATHS += -I.././mbed-os/storage/filesystem/fat/include
INCLUDE_PATHS += -I.././mbed-os/storage/filesystem/fat/include/fat
INCLUDE_PATHS += -I.././mbed-os/storage/filesystem/include
INCLUDE_PATHS += -I.././mbed-os/storage/filesystem/include/filesystem
INCLUDE_PATHS += -I.././mbed-os/storage/filesystem/littlefs
INCLUDE_PATHS += -I.././mbed-os/storage/filesystem/littlefs/include
INCLUDE_PATHS += -I.././mbed-os/storage/filesystem/littlefs/include/littlefs
INCLUDE_PATHS += -I.././mbed-os/storage/filesystem/littlefs/littlefs
INCLUDE_PATHS += -I.././mbed-os/storage/filesystem/littlefsv2
INCLUDE_PATHS += -I.././mbed-os/storage/filesystem/littlefsv2/include
INCLUDE_PATHS += -I.././mbed-os/storage/filesystem/littlefsv2/include/littlefsv2
INCLUDE_PATHS += -I.././mbed-os/storage/filesystem/littlefsv2/littlefs
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_STM
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_STM/TARGET_STM32F7
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/CMSIS
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/Legacy
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG
INCLUDE_PATHS += -I.././mbed-os/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_DISCO_F746NG
INCLUDE_PATHS += -I.././src
INCLUDE_PATHS += -I.././src/generated
INCLUDE_PATHS += -I.././src/generated/fonts
INCLUDE_PATHS += -I.././src/generated/fonts/include
INCLUDE_PATHS += -I.././src/generated/fonts/include/fonts
INCLUDE_PATHS += -I.././src/generated/gui_generated
INCLUDE_PATHS += -I.././src/generated/gui_generated/include
INCLUDE_PATHS += -I.././src/generated/gui_generated/include/gui_generated
INCLUDE_PATHS += -I.././src/generated/gui_generated/include/gui_generated/common
INCLUDE_PATHS += -I.././src/generated/gui_generated/include/gui_generated/screen1_screen
INCLUDE_PATHS += -I.././src/generated/gui_generated/include/gui_generated/screen2_screen
INCLUDE_PATHS += -I.././src/generated/images
INCLUDE_PATHS += -I.././src/generated/images/include
INCLUDE_PATHS += -I.././src/generated/texts
INCLUDE_PATHS += -I.././src/generated/texts/include
INCLUDE_PATHS += -I.././src/generated/texts/include/texts
INCLUDE_PATHS += -I.././src/gui
INCLUDE_PATHS += -I.././src/gui/include
INCLUDE_PATHS += -I.././src/gui/include/gui
INCLUDE_PATHS += -I.././src/gui/include/gui/common
INCLUDE_PATHS += -I.././src/gui/include/gui/model
INCLUDE_PATHS += -I.././src/gui/include/gui/screen1_screen
INCLUDE_PATHS += -I.././src/gui/include/gui/screen2_screen
INCLUDE_PATHS += -I..//home/beslan/MbedPrograms/DiscoF746_tgfx/mbed-os

LIBRARY_PATHS := -L.././lib/touchgfx/lib 
LIBRARIES := -ltouchgfx-float-abi-hard 
LINKER_SCRIPT ?= .././mbed-os/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TOOLCHAIN_GCC_ARM/STM32F746xG.ld

# Objects and Paths
###############################################################################
# Tools and Flags

AS      = arm-none-eabi-gcc
CC      = arm-none-eabi-gcc
CPP     = arm-none-eabi-g++
LD      = arm-none-eabi-gcc
ELF2BIN = arm-none-eabi-objcopy
PREPROC = arm-none-eabi-cpp -E -P -Wl,--gc-sections -Wl,--wrap,main -Wl,--wrap,_malloc_r -Wl,--wrap,_free_r -Wl,--wrap,_realloc_r -Wl,--wrap,_memalign_r -Wl,--wrap,_calloc_r -Wl,--wrap,exit -Wl,--wrap,atexit -Wl,-n -Wl,--wrap,printf -Wl,--wrap,sprintf -Wl,--wrap,snprintf -Wl,--wrap,vprintf -Wl,--wrap,vsprintf -Wl,--wrap,vsnprintf -Wl,--wrap,fprintf -Wl,--wrap,vfprintf -mcpu=cortex-m7 -mthumb -mfpu=fpv5-sp-d16 -mfloat-abi=hard -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fmessage-length=0 -fno-exceptions -ffunction-sections -fdata-sections -funsigned-char -MMD -fomit-frame-pointer -Os -DNDEBUG -g -DMBED_MINIMAL_PRINTF -mcpu=cortex-m7 -mthumb -mfpu=fpv5-sp-d16 -mfloat-abi=hard -DMBED_ROM_START=0x8000000 -DMBED_ROM_SIZE=0x100000 -DMBED_ROM1_START=0x200000 -DMBED_ROM1_SIZE=0x100000 -DMBED_RAM_START=0x20010000 -DMBED_RAM_SIZE=0x40000 -DMBED_RAM1_START=0x20000000 -DMBED_RAM1_SIZE=0x10000 -DMBED_BOOT_STACK_SIZE=1024 -DXIP_ENABLE=0


C_FLAGS += -c
C_FLAGS += -std=gnu11
C_FLAGS += -include
C_FLAGS += mbed_config.h
C_FLAGS += -DUSE_FULL_LL_DRIVER
C_FLAGS += -DTARGET_RTOS_M4_M7
C_FLAGS += -DTARGET_STM32F7
C_FLAGS += -DDEVICE_EMAC=1
C_FLAGS += -DDEVICE_SERIAL_FC=1
C_FLAGS += -DDEVICE_SLEEP=1
C_FLAGS += -DDEVICE_USBDEVICE=1
C_FLAGS += -DDEVICE_TRNG=1
C_FLAGS += -DTARGET_LIKE_MBED
C_FLAGS += -DTOOLCHAIN_GCC
C_FLAGS += -D__CORTEX_M7
C_FLAGS += -DTARGET_DISCO_F746NG
C_FLAGS += -DTARGET_MCU_STM32
C_FLAGS += -D__CMSIS_RTOS
C_FLAGS += -DMBED_BUILD_TIMESTAMP=1599189084.0931253
C_FLAGS += -DUSE_HAL_DRIVER
C_FLAGS += -DTARGET_STM32F746xG
C_FLAGS += -DDEVICE_STDIO_MESSAGES=1
C_FLAGS += -DDEVICE_QSPI=1
C_FLAGS += -DTARGET_STM
C_FLAGS += -DDEVICE_ANALOGIN=1
C_FLAGS += -DTRANSACTION_QUEUE_SIZE_SPI=2
C_FLAGS += -DTARGET_NAME=DISCO_F746NG
C_FLAGS += -DDEVICE_ANALOGOUT=1
C_FLAGS += -DCOMPONENT_FLASHIAP=1
C_FLAGS += -DTOOLCHAIN_GCC_ARM
C_FLAGS += -DDEVICE_SERIAL_ASYNCH=1
C_FLAGS += -DTARGET_N25Q128A
C_FLAGS += -DDEVICE_PORTINOUT=1
C_FLAGS += -DARM_MATH_CM7
C_FLAGS += -DDEVICE_WATCHDOG=1
C_FLAGS += -DTARGET_CORTEX_M
C_FLAGS += -DDEVICE_CAN=1
C_FLAGS += -DHSE_VALUE=25000000
C_FLAGS += -DDEVICE_I2CSLAVE=1
C_FLAGS += -DTARGET_RELEASE
C_FLAGS += -DSTM32F746xx
C_FLAGS += -DDEVICE_SPI=1
C_FLAGS += -DTARGET_M7
C_FLAGS += -DDEVICE_PWMOUT=1
C_FLAGS += -DEXTRA_IDLE_STACK_REQUIRED
C_FLAGS += -DDEVICE_INTERRUPTIN=1
C_FLAGS += -DDEVICE_I2C=1
C_FLAGS += -DDEVICE_RESET_REASON=1
C_FLAGS += -D__MBED_CMSIS_RTOS_CM
C_FLAGS += -DDEVICE_MPU=1
C_FLAGS += -D__MBED__=1
C_FLAGS += -DDEVICE_FLASH=1
C_FLAGS += -DDEVICE_I2C_ASYNCH=1
C_FLAGS += -DDEVICE_SPI_ASYNCH=1
C_FLAGS += -DDEVICE_PORTIN=1
C_FLAGS += -DDEVICE_SPISLAVE=1
C_FLAGS += -DCOMPONENT_QSPIF=1
C_FLAGS += -DTARGET_CORTEX
C_FLAGS += -DDEVICE_USTICKER=1
C_FLAGS += -DDEVICE_RTC=1
C_FLAGS += -DDEVICE_SERIAL=1
C_FLAGS += -DTARGET_FF_ARDUINO
C_FLAGS += -DTARGET_LIKE_CORTEX_M7
C_FLAGS += -DDEVICE_LPTICKER=1
C_FLAGS += -D__FPU_PRESENT=1
C_FLAGS += -DDEVICE_CRC=1
C_FLAGS += -DMBED_TICKLESS
C_FLAGS += -DTARGET_MCU_STM32F7
C_FLAGS += -DDEVICE_PORTOUT=1
C_FLAGS += -include
C_FLAGS += mbed_config.h
C_FLAGS += -c
C_FLAGS += -std=gnu11
C_FLAGS += -Wall
C_FLAGS += -Wextra
C_FLAGS += -Wno-unused-parameter
C_FLAGS += -Wno-missing-field-initializers
C_FLAGS += -fmessage-length=0
C_FLAGS += -fno-exceptions
C_FLAGS += -ffunction-sections
C_FLAGS += -fdata-sections
C_FLAGS += -funsigned-char
C_FLAGS += -MMD
C_FLAGS += -fomit-frame-pointer
C_FLAGS += -Os
C_FLAGS += -DNDEBUG
C_FLAGS += -g
C_FLAGS += -DMBED_MINIMAL_PRINTF
C_FLAGS += -mcpu=cortex-m7
C_FLAGS += -mthumb
C_FLAGS += -mfpu=fpv5-sp-d16
C_FLAGS += -mfloat-abi=hard
C_FLAGS += -DMBED_ROM_START=0x8000000
C_FLAGS += -DMBED_ROM_SIZE=0x100000
C_FLAGS += -DMBED_ROM1_START=0x200000
C_FLAGS += -DMBED_ROM1_SIZE=0x100000
C_FLAGS += -DMBED_RAM_START=0x20010000
C_FLAGS += -DMBED_RAM_SIZE=0x40000
C_FLAGS += -DMBED_RAM1_START=0x20000000
C_FLAGS += -DMBED_RAM1_SIZE=0x10000

CXX_FLAGS += -c
CXX_FLAGS += -std=gnu++14
CXX_FLAGS += -fno-rtti
CXX_FLAGS += -Wvla
CXX_FLAGS += -include
CXX_FLAGS += mbed_config.h
CXX_FLAGS += -DUSE_FULL_LL_DRIVER
CXX_FLAGS += -DTARGET_RTOS_M4_M7
CXX_FLAGS += -DTARGET_STM32F7
CXX_FLAGS += -DDEVICE_EMAC=1
CXX_FLAGS += -DDEVICE_SERIAL_FC=1
CXX_FLAGS += -DDEVICE_SLEEP=1
CXX_FLAGS += -DDEVICE_USBDEVICE=1
CXX_FLAGS += -DDEVICE_TRNG=1
CXX_FLAGS += -DTARGET_LIKE_MBED
CXX_FLAGS += -DTOOLCHAIN_GCC
CXX_FLAGS += -D__CORTEX_M7
CXX_FLAGS += -DTARGET_DISCO_F746NG
CXX_FLAGS += -DTARGET_MCU_STM32
CXX_FLAGS += -D__CMSIS_RTOS
CXX_FLAGS += -DMBED_BUILD_TIMESTAMP=1599189084.0931253
CXX_FLAGS += -DUSE_HAL_DRIVER
CXX_FLAGS += -DTARGET_STM32F746xG
CXX_FLAGS += -DDEVICE_STDIO_MESSAGES=1
CXX_FLAGS += -DDEVICE_QSPI=1
CXX_FLAGS += -DTARGET_STM
CXX_FLAGS += -DDEVICE_ANALOGIN=1
CXX_FLAGS += -DTRANSACTION_QUEUE_SIZE_SPI=2
CXX_FLAGS += -DTARGET_NAME=DISCO_F746NG
CXX_FLAGS += -DDEVICE_ANALOGOUT=1
CXX_FLAGS += -DCOMPONENT_FLASHIAP=1
CXX_FLAGS += -DTOOLCHAIN_GCC_ARM
CXX_FLAGS += -DDEVICE_SERIAL_ASYNCH=1
CXX_FLAGS += -DTARGET_N25Q128A
CXX_FLAGS += -DDEVICE_PORTINOUT=1
CXX_FLAGS += -DARM_MATH_CM7
CXX_FLAGS += -DDEVICE_WATCHDOG=1
CXX_FLAGS += -DTARGET_CORTEX_M
CXX_FLAGS += -DDEVICE_CAN=1
CXX_FLAGS += -DHSE_VALUE=25000000
CXX_FLAGS += -DDEVICE_I2CSLAVE=1
CXX_FLAGS += -DTARGET_RELEASE
CXX_FLAGS += -DSTM32F746xx
CXX_FLAGS += -DDEVICE_SPI=1
CXX_FLAGS += -DTARGET_M7
CXX_FLAGS += -DDEVICE_PWMOUT=1
CXX_FLAGS += -DEXTRA_IDLE_STACK_REQUIRED
CXX_FLAGS += -DDEVICE_INTERRUPTIN=1
CXX_FLAGS += -DDEVICE_I2C=1
CXX_FLAGS += -DDEVICE_RESET_REASON=1
CXX_FLAGS += -D__MBED_CMSIS_RTOS_CM
CXX_FLAGS += -DDEVICE_MPU=1
CXX_FLAGS += -D__MBED__=1
CXX_FLAGS += -DDEVICE_FLASH=1
CXX_FLAGS += -DDEVICE_I2C_ASYNCH=1
CXX_FLAGS += -DDEVICE_SPI_ASYNCH=1
CXX_FLAGS += -DDEVICE_PORTIN=1
CXX_FLAGS += -DDEVICE_SPISLAVE=1
CXX_FLAGS += -DCOMPONENT_QSPIF=1
CXX_FLAGS += -DTARGET_CORTEX
CXX_FLAGS += -DDEVICE_USTICKER=1
CXX_FLAGS += -DDEVICE_RTC=1
CXX_FLAGS += -DDEVICE_SERIAL=1
CXX_FLAGS += -DTARGET_FF_ARDUINO
CXX_FLAGS += -DTARGET_LIKE_CORTEX_M7
CXX_FLAGS += -DDEVICE_LPTICKER=1
CXX_FLAGS += -D__FPU_PRESENT=1
CXX_FLAGS += -DDEVICE_CRC=1
CXX_FLAGS += -DMBED_TICKLESS
CXX_FLAGS += -DTARGET_MCU_STM32F7
CXX_FLAGS += -DDEVICE_PORTOUT=1
CXX_FLAGS += -include
CXX_FLAGS += mbed_config.h
CXX_FLAGS += -c
CXX_FLAGS += -std=gnu++14
CXX_FLAGS += -fno-rtti
CXX_FLAGS += -Wvla
CXX_FLAGS += -Wall
CXX_FLAGS += -Wextra
CXX_FLAGS += -Wno-unused-parameter
CXX_FLAGS += -Wno-missing-field-initializers
CXX_FLAGS += -fmessage-length=0
CXX_FLAGS += -fno-exceptions
CXX_FLAGS += -ffunction-sections
CXX_FLAGS += -fdata-sections
CXX_FLAGS += -funsigned-char
CXX_FLAGS += -MMD
CXX_FLAGS += -fomit-frame-pointer
CXX_FLAGS += -Os
CXX_FLAGS += -DNDEBUG
CXX_FLAGS += -g
CXX_FLAGS += -DMBED_MINIMAL_PRINTF
CXX_FLAGS += -mcpu=cortex-m7
CXX_FLAGS += -mthumb
CXX_FLAGS += -mfpu=fpv5-sp-d16
CXX_FLAGS += -mfloat-abi=hard
CXX_FLAGS += -DMBED_ROM_START=0x8000000
CXX_FLAGS += -DMBED_ROM_SIZE=0x100000
CXX_FLAGS += -DMBED_ROM1_START=0x200000
CXX_FLAGS += -DMBED_ROM1_SIZE=0x100000
CXX_FLAGS += -DMBED_RAM_START=0x20010000
CXX_FLAGS += -DMBED_RAM_SIZE=0x40000
CXX_FLAGS += -DMBED_RAM1_START=0x20000000
CXX_FLAGS += -DMBED_RAM1_SIZE=0x10000

ASM_FLAGS += -c
ASM_FLAGS += -x
ASM_FLAGS += assembler-with-cpp
ASM_FLAGS += -DUSE_FULL_LL_DRIVER
ASM_FLAGS += -DHSE_VALUE=25000000
ASM_FLAGS += -DSTM32F746xx
ASM_FLAGS += -DTRANSACTION_QUEUE_SIZE_SPI=2
ASM_FLAGS += -D__CORTEX_M7
ASM_FLAGS += -DEXTRA_IDLE_STACK_REQUIRED
ASM_FLAGS += -D__CMSIS_RTOS
ASM_FLAGS += -DUSE_HAL_DRIVER
ASM_FLAGS += -D__MBED_CMSIS_RTOS_CM
ASM_FLAGS += -D__FPU_PRESENT=1
ASM_FLAGS += -DARM_MATH_CM7
ASM_FLAGS += -DMBED_TICKLESS
ASM_FLAGS += -I..
ASM_FLAGS += -I../lib
ASM_FLAGS += -I../lib/BSP_DISCO_F746NG
ASM_FLAGS += -I../lib/BSP_DISCO_F746NG/Drivers
ASM_FLAGS += -I../lib/BSP_DISCO_F746NG/Drivers/BSP
ASM_FLAGS += -I../lib/BSP_DISCO_F746NG/Drivers/BSP/Components
ASM_FLAGS += -I../lib/BSP_DISCO_F746NG/Drivers/BSP/Components/Common
ASM_FLAGS += -I../lib/BSP_DISCO_F746NG/Drivers/BSP/Components/ft5336
ASM_FLAGS += -I../lib/BSP_DISCO_F746NG/Drivers/BSP/Components/n25q128a
ASM_FLAGS += -I../lib/BSP_DISCO_F746NG/Drivers/BSP/Components/ov9655
ASM_FLAGS += -I../lib/BSP_DISCO_F746NG/Drivers/BSP/Components/rk043fn48h
ASM_FLAGS += -I../lib/BSP_DISCO_F746NG/Drivers/BSP/Components/wm8994
ASM_FLAGS += -I../lib/BSP_DISCO_F746NG/Drivers/BSP/STM32746G-Discovery
ASM_FLAGS += -I../lib/BSP_DISCO_F746NG/Utilities
ASM_FLAGS += -I../lib/BSP_DISCO_F746NG/Utilities/Fonts
ASM_FLAGS += -I../lib/LCD_DISCO_F746NG
ASM_FLAGS += -I../lib/touchgfx
ASM_FLAGS += -I../lib/touchgfx/framework
ASM_FLAGS += -I../lib/touchgfx/framework/include
ASM_FLAGS += -I../lib/touchgfx/framework/include/common
ASM_FLAGS += -I../lib/touchgfx/framework/include/mvp
ASM_FLAGS += -I../lib/touchgfx/framework/include/platform
ASM_FLAGS += -I../lib/touchgfx/framework/include/platform/core
ASM_FLAGS += -I../lib/touchgfx/framework/include/platform/driver
ASM_FLAGS += -I../lib/touchgfx/framework/include/platform/driver/button
ASM_FLAGS += -I../lib/touchgfx/framework/include/platform/driver/i2c
ASM_FLAGS += -I../lib/touchgfx/framework/include/platform/driver/lcd
ASM_FLAGS += -I../lib/touchgfx/framework/include/platform/driver/touch
ASM_FLAGS += -I../lib/touchgfx/framework/include/platform/hal
ASM_FLAGS += -I../lib/touchgfx/framework/include/platform/hal/simulator
ASM_FLAGS += -I../lib/touchgfx/framework/include/platform/hal/simulator/sdl2
ASM_FLAGS += -I../lib/touchgfx/framework/include/platform/hal/simulator/sdl2/vendor
ASM_FLAGS += -I../lib/touchgfx/framework/include/platform/hal/simulator/sdl2/vendor/SDL2
ASM_FLAGS += -I../lib/touchgfx/framework/include/touchgfx
ASM_FLAGS += -I../lib/touchgfx/framework/include/touchgfx/canvas_widget_renderer
ASM_FLAGS += -I../lib/touchgfx/framework/include/touchgfx/containers
ASM_FLAGS += -I../lib/touchgfx/framework/include/touchgfx/containers/buttons
ASM_FLAGS += -I../lib/touchgfx/framework/include/touchgfx/containers/clock
ASM_FLAGS += -I../lib/touchgfx/framework/include/touchgfx/containers/progress_indicators
ASM_FLAGS += -I../lib/touchgfx/framework/include/touchgfx/containers/scrollers
ASM_FLAGS += -I../lib/touchgfx/framework/include/touchgfx/events
ASM_FLAGS += -I../lib/touchgfx/framework/include/touchgfx/hal
ASM_FLAGS += -I../lib/touchgfx/framework/include/touchgfx/lcd
ASM_FLAGS += -I../lib/touchgfx/framework/include/touchgfx/mixins
ASM_FLAGS += -I../lib/touchgfx/framework/include/touchgfx/transforms
ASM_FLAGS += -I../lib/touchgfx/framework/include/touchgfx/transitions
ASM_FLAGS += -I../lib/touchgfx/framework/include/touchgfx/widgets
ASM_FLAGS += -I../lib/touchgfx/framework/include/touchgfx/widgets/canvas
ASM_FLAGS += -I../mbed-os
ASM_FLAGS += -I../mbed-os/cmsis
ASM_FLAGS += -I../mbed-os/cmsis/CMSIS_5
ASM_FLAGS += -I../mbed-os/cmsis/CMSIS_5/CMSIS
ASM_FLAGS += -I../mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2
ASM_FLAGS += -I../mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/Include
ASM_FLAGS += -I../mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX
ASM_FLAGS += -I../mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Config
ASM_FLAGS += -I../mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Include
ASM_FLAGS += -I../mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Include1
ASM_FLAGS += -I../mbed-os/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source
ASM_FLAGS += -I../mbed-os/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M
ASM_FLAGS += -I../mbed-os/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Include
ASM_FLAGS += -I../mbed-os/cmsis/device
ASM_FLAGS += -I../mbed-os/cmsis/device/RTE
ASM_FLAGS += -I../mbed-os/cmsis/device/RTE/include
ASM_FLAGS += -I../mbed-os/cmsis/device/rtos
ASM_FLAGS += -I../mbed-os/cmsis/device/rtos/include
ASM_FLAGS += -I../mbed-os/connectivity
ASM_FLAGS += -I../mbed-os/connectivity/libraries
ASM_FLAGS += -I../mbed-os/connectivity/libraries/nanostack-libservice
ASM_FLAGS += -I../mbed-os/connectivity/libraries/nanostack-libservice/mbed-client-libservice
ASM_FLAGS += -I../mbed-os/connectivity/libraries/nanostack-libservice/mbed-client-libservice/platform
ASM_FLAGS += -I../mbed-os/drivers
ASM_FLAGS += -I../mbed-os/drivers/include
ASM_FLAGS += -I../mbed-os/drivers/include/drivers
ASM_FLAGS += -I../mbed-os/drivers/include/drivers/internal
ASM_FLAGS += -I../mbed-os/events
ASM_FLAGS += -I../mbed-os/events/include
ASM_FLAGS += -I../mbed-os/events/include/events
ASM_FLAGS += -I../mbed-os/events/include/events/internal
ASM_FLAGS += -I../mbed-os/features
ASM_FLAGS += -I../mbed-os/features/frameworks
ASM_FLAGS += -I../mbed-os/features/frameworks/mbed-trace
ASM_FLAGS += -I../mbed-os/features/frameworks/mbed-trace/mbed-trace
ASM_FLAGS += -I../mbed-os/hal
ASM_FLAGS += -I../mbed-os/hal/include
ASM_FLAGS += -I../mbed-os/hal/include/hal
ASM_FLAGS += -I../mbed-os/hal/usb
ASM_FLAGS += -I../mbed-os/hal/usb/include
ASM_FLAGS += -I../mbed-os/hal/usb/include/usb
ASM_FLAGS += -I../mbed-os/platform
ASM_FLAGS += -I../mbed-os/platform/cxxsupport
ASM_FLAGS += -I../mbed-os/platform/include
ASM_FLAGS += -I../mbed-os/platform/include/platform
ASM_FLAGS += -I../mbed-os/platform/include/platform/internal
ASM_FLAGS += -I../mbed-os/platform/source
ASM_FLAGS += -I../mbed-os/platform/source/minimal-printf
ASM_FLAGS += -I../mbed-os/rtos
ASM_FLAGS += -I../mbed-os/rtos/include
ASM_FLAGS += -I../mbed-os/rtos/include/rtos
ASM_FLAGS += -I../mbed-os/rtos/include/rtos/internal
ASM_FLAGS += -I../mbed-os/rtos/source
ASM_FLAGS += -I../mbed-os/storage
ASM_FLAGS += -I../mbed-os/storage/blockdevice
ASM_FLAGS += -I../mbed-os/storage/blockdevice/COMPONENT_FLASHIAP
ASM_FLAGS += -I../mbed-os/storage/blockdevice/COMPONENT_FLASHIAP/include
ASM_FLAGS += -I../mbed-os/storage/blockdevice/COMPONENT_FLASHIAP/include/FlashIAP
ASM_FLAGS += -I../mbed-os/storage/blockdevice/COMPONENT_QSPIF
ASM_FLAGS += -I../mbed-os/storage/blockdevice/COMPONENT_QSPIF/include
ASM_FLAGS += -I../mbed-os/storage/blockdevice/COMPONENT_QSPIF/include/QSPIF
ASM_FLAGS += -I../mbed-os/storage/blockdevice/include
ASM_FLAGS += -I../mbed-os/storage/blockdevice/include/blockdevice
ASM_FLAGS += -I../mbed-os/storage/filesystem
ASM_FLAGS += -I../mbed-os/storage/filesystem/fat
ASM_FLAGS += -I../mbed-os/storage/filesystem/fat/ChaN
ASM_FLAGS += -I../mbed-os/storage/filesystem/fat/include
ASM_FLAGS += -I../mbed-os/storage/filesystem/fat/include/fat
ASM_FLAGS += -I../mbed-os/storage/filesystem/include
ASM_FLAGS += -I../mbed-os/storage/filesystem/include/filesystem
ASM_FLAGS += -I../mbed-os/storage/filesystem/littlefs
ASM_FLAGS += -I../mbed-os/storage/filesystem/littlefs/include
ASM_FLAGS += -I../mbed-os/storage/filesystem/littlefs/include/littlefs
ASM_FLAGS += -I../mbed-os/storage/filesystem/littlefs/littlefs
ASM_FLAGS += -I../mbed-os/storage/filesystem/littlefsv2
ASM_FLAGS += -I../mbed-os/storage/filesystem/littlefsv2/include
ASM_FLAGS += -I../mbed-os/storage/filesystem/littlefsv2/include/littlefsv2
ASM_FLAGS += -I../mbed-os/storage/filesystem/littlefsv2/littlefs
ASM_FLAGS += -I../mbed-os/targets/TARGET_STM
ASM_FLAGS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32F7
ASM_FLAGS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW
ASM_FLAGS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/CMSIS
ASM_FLAGS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver
ASM_FLAGS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/Legacy
ASM_FLAGS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG
ASM_FLAGS += -I../mbed-os/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_DISCO_F746NG
ASM_FLAGS += -I../src
ASM_FLAGS += -I../src/generated
ASM_FLAGS += -I../src/generated/fonts
ASM_FLAGS += -I../src/generated/fonts/include
ASM_FLAGS += -I../src/generated/fonts/include/fonts
ASM_FLAGS += -I../src/generated/gui_generated
ASM_FLAGS += -I../src/generated/gui_generated/include
ASM_FLAGS += -I../src/generated/gui_generated/include/gui_generated
ASM_FLAGS += -I../src/generated/gui_generated/include/gui_generated/common
ASM_FLAGS += -I../src/generated/gui_generated/include/gui_generated/screen1_screen
ASM_FLAGS += -I../src/generated/gui_generated/include/gui_generated/screen2_screen
ASM_FLAGS += -I../src/generated/images
ASM_FLAGS += -I../src/generated/images/include
ASM_FLAGS += -I../src/generated/texts
ASM_FLAGS += -I../src/generated/texts/include
ASM_FLAGS += -I../src/generated/texts/include/texts
ASM_FLAGS += -I../src/gui
ASM_FLAGS += -I../src/gui/include
ASM_FLAGS += -I../src/gui/include/gui
ASM_FLAGS += -I../src/gui/include/gui/common
ASM_FLAGS += -I../src/gui/include/gui/model
ASM_FLAGS += -I../src/gui/include/gui/screen1_screen
ASM_FLAGS += -I../src/gui/include/gui/screen2_screen
ASM_FLAGS += -I/home/beslan/MbedPrograms/DiscoF746_tgfx/mbed-os
ASM_FLAGS += -include
ASM_FLAGS += ./mbed_config.h
ASM_FLAGS += -c
ASM_FLAGS += -x
ASM_FLAGS += assembler-with-cpp
ASM_FLAGS += -Wall
ASM_FLAGS += -Wextra
ASM_FLAGS += -Wno-unused-parameter
ASM_FLAGS += -Wno-missing-field-initializers
ASM_FLAGS += -fmessage-length=0
ASM_FLAGS += -fno-exceptions
ASM_FLAGS += -ffunction-sections
ASM_FLAGS += -fdata-sections
ASM_FLAGS += -funsigned-char
ASM_FLAGS += -MMD
ASM_FLAGS += -fomit-frame-pointer
ASM_FLAGS += -Os
ASM_FLAGS += -DNDEBUG
ASM_FLAGS += -g
ASM_FLAGS += -DMBED_MINIMAL_PRINTF
ASM_FLAGS += -mcpu=cortex-m7
ASM_FLAGS += -mthumb
ASM_FLAGS += -mfpu=fpv5-sp-d16
ASM_FLAGS += -mfloat-abi=hard


LD_FLAGS :=-Wl,--gc-sections -Wl,--wrap,main -Wl,--wrap,_malloc_r -Wl,--wrap,_free_r -Wl,--wrap,_realloc_r -Wl,--wrap,_memalign_r -Wl,--wrap,_calloc_r -Wl,--wrap,exit -Wl,--wrap,atexit -Wl,-n -Wl,--wrap,printf -Wl,--wrap,sprintf -Wl,--wrap,snprintf -Wl,--wrap,vprintf -Wl,--wrap,vsprintf -Wl,--wrap,vsnprintf -Wl,--wrap,fprintf -Wl,--wrap,vfprintf -mcpu=cortex-m7 -mthumb -mfpu=fpv5-sp-d16 -mfloat-abi=hard -DMBED_ROM_START=0x8000000 -DMBED_ROM_SIZE=0x100000 -DMBED_ROM1_START=0x200000 -DMBED_ROM1_SIZE=0x100000 -DMBED_RAM_START=0x20010000 -DMBED_RAM_SIZE=0x40000 -DMBED_RAM1_START=0x20000000 -DMBED_RAM1_SIZE=0x10000 -DMBED_BOOT_STACK_SIZE=1024 -DXIP_ENABLE=0 
LD_SYS_LIBS :=-Wl,--start-group -lstdc++ -lsupc++ -lm -lc -lgcc -lnosys -ltouchgfx-float-abi-hard -Wl,--end-group

# Tools and Flags
###############################################################################
# Rules

.PHONY: all lst size


all: $(PROJECT).bin $(PROJECT).hex size


.s.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Assemble: $(notdir $<)"
  
	@$(AS) -c $(ASM_FLAGS) -o $@ $<
  


.S.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Assemble: $(notdir $<)"
  
	@$(AS) -c $(ASM_FLAGS) -o $@ $<
  

.c.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Compile: $(notdir $<)"
	@$(CC) $(C_FLAGS) $(INCLUDE_PATHS) -o $@ $<

.cpp.o:
	+@$(call MAKEDIR,$(dir $@))
	+@echo "Compile: $(notdir $<)"
	@$(CPP) $(CXX_FLAGS) $(INCLUDE_PATHS) -o $@ $<


$(PROJECT).link_script.ld: $(LINKER_SCRIPT)
	@$(PREPROC) $< -o $@



$(PROJECT).elf: $(OBJECTS) $(SYS_OBJECTS) $(PROJECT).link_script.ld 
	+@echo "$(filter %.o, $^)" > .link_options.txt
	+@echo "link: $(notdir $@)"
	@$(LD) $(LD_FLAGS) -T $(filter-out %.o, $^) $(LIBRARY_PATHS) --output $@ @.link_options.txt $(LIBRARIES) $(LD_SYS_LIBS)


$(PROJECT).bin: $(PROJECT).elf
	$(ELF2BIN) -O binary $< $@
	+@echo "===== bin file ready to flash: $(OBJDIR)/$@ =====" 

$(PROJECT).hex: $(PROJECT).elf
	$(ELF2BIN) -O ihex $< $@


# Rules
###############################################################################
# Dependencies

DEPS = $(OBJECTS:.o=.d) $(SYS_OBJECTS:.o=.d)
-include $(DEPS)
endif

# Dependencies
###############################################################################
# Catch-all

%: ;

# Catch-all
###############################################################################
